---
- hosts: workers
  become: yes
  tasks:
  - name: create folder
    shell: mkdir -p /root/caliper-bench/azure-3nodes/caliper-benchmarks/networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/config
  
- hosts: client
  become: yes
  gather_facts: no
  tasks:  
  - name: generate cryto files 
    shell: bash generate.sh
    args:
      chdir: /root/caliper-bench/azure-3nodes/caliper-benchmarks/networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/config/

# - hosts: workers
#   tasks:
#     - name: Transfer file from client to workers
#       synchronize:
#         src: /root/caliper-bench/azure-3nodes/caliper-benchmarks/networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/config/
#         dest: /root/caliper-bench/azure-3nodes/caliper-benchmarks/networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/config/
#       delegate_to: client

# - hosts: client
#   become: yes
#   gather_facts: no
#   tasks:    
  
#   - name: Monitor 
#     shell: bash start.sh
#     args:
#       chdir: /root/caliper-bench/azure-3nodes/monitor/
  
#   - name: Test 
#     cmd: npx caliper benchmark run --caliper-benchconfig benchmarks/samples/fabric/marbles/config.yaml --caliper-networkconfig networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/fabric-ccp-go-tls.yaml --caliper-workspace .
#     args:
#       chdir: /root/caliper-bench/azure-3nodes/caliper-benchmarks/
