---       
- hosts: master
  tasks:    
    
  - name: Init a new swarm with default parameters
    docker_swarm:
      state: present
 
        
        
- hosts: worker
  tasks: 
  
  - name: Add nodes
    docker_swarm:
      state: join
      advertise_addr: 192.168.1.2
      join_token: SWMTKN-1--xxxxx
      remote_addrs: [ '192.168.1.1:2377' ]
