- hosts: workers
  become: yes
  gather_facts: no
  tasks:    
   - name: Transfer file from client to workers
     synchronize:
       src: /root/caliper-bench/azure-3nodes/caliper-benchmarks/networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/config/configtx.yaml
       dest: /root/caliper-bench/azure-3nodes/caliper-benchmarks/networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/config/configtx.yaml
     delegate_to: client
