- hosts: client
  become: yes
  gather_facts: no
  tasks:  
  - name: host files 
    shell: cat /etc/hosts
#     args:
#       chdir: /root/caliper-bench/azure-3nodes/caliper-benchmarks/networks/fabric/fabric-v1.4.1/swarm-3org1peer-raft/config/


